import { Store, Product, Order, RiderProfile, PlatformAnalytics, Review } from "@/types";

// INITIAL SEED STORES (African & Fast Food Marketplace)
export const INITIAL_STORES: Store[] = [
  {
    id: "store-1",
    name: "FoodLAND Restaurant",
    slug: "foodland-restaurant",
    description: "Authentic African delicacies, Jollof Rice, Fried Rice, Pounded Yam & Egusi Soup.",
    logo: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=200&q=80",
    banner: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1000&q=80",
    category: "restaurant",
    cuisineType: "African • Rice",
    rating: 4.8,
    reviewCount: 342,
    deliveryTime: "25-35 min",
    deliveryFee: 450,
    minOrder: 1500,
    address: "24 Okpe Road, Sapele, Delta State",
    isOpening: true,
    isVerified: true,
    status: "active",
    phone: "+234 803 123 4567",
  },
  {
    id: "store-2",
    name: "Mama Cass Kitchen",
    slug: "mama-cass-kitchen",
    description: "Homestyle Traditional Nigerian Soups, Pepper Soup, Fisherman Soup & Plantain.",
    logo: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=200&q=80",
    banner: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80",
    category: "restaurant",
    cuisineType: "Traditional • Soups",
    rating: 4.7,
    reviewCount: 215,
    deliveryTime: "30-40 min",
    deliveryFee: 500,
    minOrder: 2000,
    address: "12 Mission Road, Sapele, Delta State",
    isOpening: true,
    isVerified: true,
    status: "active",
    phone: "+234 802 987 6543",
  },
  {
    id: "store-3",
    name: "SmallChops & Grills Express",
    slug: "smallchops-grills-express",
    description: "Crispy Samosa, Spring Rolls, Puff-Puff, Suya & Grilled Chicken Wings.",
    logo: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=200&q=80",
    banner: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1000&q=80",
    category: "restaurant",
    cuisineType: "Finger Food • Suya",
    rating: 4.9,
    reviewCount: 512,
    deliveryTime: "15-25 min",
    deliveryFee: 350,
    minOrder: 1000,
    address: "88 Sapele-Warri Road, Sapele",
    isOpening: true,
    isVerified: true,
    status: "active",
    phone: "+234 814 555 7788",
  },
  {
    id: "store-4",
    name: "Sapele Central Supermarket",
    slug: "sapele-central-supermarket",
    description: "Groceries, Fresh Fruits, Drinks, Toiletries, Dairy & Household Items.",
    logo: "https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=200&q=80",
    banner: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?auto=format&fit=crop&w=1000&q=80",
    category: "supermarket",
    cuisineType: "Groceries • Essentials",
    rating: 4.6,
    reviewCount: 180,
    deliveryTime: "20-30 min",
    deliveryFee: 400,
    minOrder: 1200,
    address: "5 Market Road, Sapele",
    isOpening: true,
    isVerified: true,
    status: "active",
    phone: "+234 805 111 2233",
  },
  {
    id: "store-5",
    name: "HealthFirst Pharmacy",
    slug: "healthfirst-pharmacy",
    description: "Prescription drugs, Vitamins, First Aid, Hygiene & Wellness essentials.",
    logo: "https://images.unsplash.com/photo-1586015555751-63bb77f4322a?auto=format&fit=crop&w=200&q=80",
    banner: "https://images.unsplash.com/photo-1631549912264-377863931b47?auto=format&fit=crop&w=1000&q=80",
    category: "pharmacy",
    cuisineType: "Meds • Wellness",
    rating: 4.9,
    reviewCount: 94,
    deliveryTime: "15-20 min",
    deliveryFee: 300,
    minOrder: 800,
    address: "14 Hospital Road, Sapele",
    isOpening: true,
    isVerified: true,
    status: "active",
    phone: "+234 809 333 4455",
  },
];

// INITIAL SEED PRODUCTS
export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    storeId: "store-1",
    name: "Smokey Party Jollof Rice + Fried Plantain & Chicken",
    description: "Fragrant smokey wood-fired Nigerian Jollof rice served with ripe sweet fried plantain and seasoned fried chicken quarter.",
    price: 3500,
    image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&w=600&q=80",
    category: "Mains",
    inStock: true,
    rating: 4.9,
    preparationTimeMinutes: 20,
    options: [
      { id: "opt-1", name: "Extra Fried Chicken", price: 1200 },
      { id: "opt-2", name: "Add Coleslaw", price: 500 },
      { id: "opt-3", name: "Add Boiled Egg", price: 300 },
    ],
  },
  {
    id: "prod-2",
    storeId: "store-1",
    name: "Pounded Yam with Goat Meat Egusi Soup",
    description: "Smooth velvety pounded yam served with rich melon Egusi soup loaded with tender goat meat and stockfish.",
    price: 4200,
    image: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=600&q=80",
    category: "Swallow & Soups",
    inStock: true,
    rating: 4.8,
    preparationTimeMinutes: 25,
    options: [
      { id: "opt-4", name: "Extra Goat Meat", price: 1500 },
      { id: "opt-5", name: "Add Assorted Meat", price: 1000 },
    ],
  },
  {
    id: "prod-3",
    storeId: "store-2",
    name: "Sapele Special Catfish Pepper Soup",
    description: "Freshly caught catfish cooked in aromatic Delta herbal spices, chili pepper, and fresh scented leaves.",
    price: 4500,
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80",
    category: "Pepper Soup",
    inStock: true,
    rating: 4.9,
    preparationTimeMinutes: 25,
  },
  {
    id: "prod-4",
    storeId: "store-3",
    name: "Mega Smallchops Platter (30 Pieces)",
    description: "Crispy Samosas, Spring Rolls, Puff-Puff, Gizzard & Spicy Beef Suya strips.",
    price: 5500,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80",
    category: "Finger Foods",
    inStock: true,
    rating: 5.0,
    preparationTimeMinutes: 15,
  },
  {
    id: "prod-5",
    storeId: "store-4",
    name: "Fresh Whole Milk 1L",
    description: "Pure pasteurized whole milk, rich in calcium and vitamins.",
    price: 1800,
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=600&q=80",
    category: "Dairy",
    inStock: true,
  },
  {
    id: "prod-6",
    storeId: "store-5",
    name: "Vitamin C 1000mg Effervescent (20 Tablets)",
    description: "High potency immune support with Zine and Bioflavonoids.",
    price: 2500,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    category: "Vitamins",
    inStock: true,
  },
];

// INITIAL RIDERS
export const INITIAL_RIDERS: RiderProfile[] = [
  {
    id: "rider-1",
    name: "Emmanuel Okafor",
    email: "emmanuel.rider@novo.ng",
    phone: "+234 812 345 6789",
    role: "rider",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    address: "Okpe Road, Sapele",
    createdAt: new Date().toISOString(),
    isOnline: true,
    isVerified: true,
    verificationStatus: "verified",
    vehicleType: "motorcycle",
    vehiclePlate: "SL-884-XY",
    rating: 4.9,
    totalDeliveries: 428,
    earningsToday: 14500,
    earningsThisWeek: 68000,
    tipsToday: 2500,
  },
  {
    id: "rider-2",
    name: "Blessing Akpan",
    email: "blessing.rider@novo.ng",
    phone: "+234 816 777 8899",
    role: "rider",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    address: "Market Road, Sapele",
    createdAt: new Date().toISOString(),
    isOnline: true,
    isVerified: true,
    verificationStatus: "verified",
    vehicleType: "motorcycle",
    vehiclePlate: "SP-102-AB",
    rating: 4.8,
    totalDeliveries: 312,
    earningsToday: 11200,
    earningsThisWeek: 54000,
    tipsToday: 1800,
  },
];

// INITIAL ORDERS
export const INITIAL_ORDERS: Order[] = [
  {
    id: "ORD-9824",
    customerId: "cust-1",
    customerName: "Godswill Okenrenkporo",
    customerPhone: "+234 802 111 9900",
    deliveryAddress: "Apartment 4B, Palm Grove Estate, Okpe Road, Sapele",
    storeId: "store-1",
    storeName: "FoodLAND Restaurant",
    storeAddress: "24 Okpe Road, Sapele",
    items: [
      {
        product: INITIAL_PRODUCTS[0],
        quantity: 2,
        selectedOptions: [INITIAL_PRODUCTS[0].options![0]],
      },
    ],
    subtotal: 9400,
    deliveryFee: 450,
    serviceFee: 200,
    tip: 500,
    total: 10550,
    status: "preparing",
    paymentMethod: "card",
    paymentStatus: "paid",
    riderId: "rider-1",
    riderName: "Emmanuel Okafor",
    riderPhone: "+234 812 345 6789",
    riderPhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    pickupCode: "4819",
    estimatedDeliveryMinutes: 20,
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
];

// FASTAPI READY SERVICE INTERFACE FUNCTIONS
export const apiService = {
  getStores: async (): Promise<Store[]> => {
    return Promise.resolve(INITIAL_STORES);
  },
  getProducts: async (storeId?: string): Promise<Product[]> => {
    if (storeId) {
      return Promise.resolve(INITIAL_PRODUCTS.filter((p) => p.storeId === storeId));
    }
    return Promise.resolve(INITIAL_PRODUCTS);
  },
  getOrders: async (): Promise<Order[]> => {
    return Promise.resolve(INITIAL_ORDERS);
  },
  getRiders: async (): Promise<RiderProfile[]> => {
    return Promise.resolve(INITIAL_RIDERS);
  },
  getAnalytics: async (): Promise<PlatformAnalytics> => {
    return Promise.resolve({
      totalRevenue: 1245000,
      totalOrders: 1420,
      activeStoresCount: INITIAL_STORES.length,
      activeRidersCount: INITIAL_RIDERS.length,
      totalCustomersCount: 3890,
      gmvToday: 185400,
      commissionEarned: 18540,
    });
  },
};
